#Salesforce config
sdfc:
  clientId: "dummy"
  clientSecret: "dummy"
  callbackPath: "/api/v1/callback"
  authorizePath: "/api/v1/authorize"
  externalUrl: "http://localhost:8081/api/v1/callback"
  authorizeUrl: "https://login.salesforce.com/services/oauth2/authorize"
  accessTokenUrl: "https://login.salesforce.com/services/oauth2/token"
